import Head from 'next/head'
import React from 'react'

type Props = {
  signIn: (provider?: string) => any;
  isAuth: boolean
}

function Appbar({signIn, isAuth}: Props) {
  return (
    <>
    <Head>
      <title>Create T3 App</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <header className='w-screen h-16 px-4 text-gray-700 dark:text-gray-500 bg-gray-300 dark:bg-gray-900 flex justify-between items-center'>
      <div className="">
        LOGO
      </div>
      <div className="flex">
        {!isAuth ? (<button className='btn-1' onClick={()=>{signIn()}} aria-label='Sign in button'>Sign in</button>) : null}
        <div className="w-12 h-12 mx-2 rounded-full overflow-hidden bg-gray-400 dark:bg-gray-600"></div>
      </div>
    </header>
    </>
  )
}

export default Appbar